### ISSUE TITLE
Feature request: ability to customise runner name to create multiple ones

### ISSUE THREAD

**Issue by yuravk** [NextChapterSoftware/ec2-action-builder#22]
The ability to customise runner name `runs-on: ${{ github.run_id }}` is required.

That will be useful in matrix.

**Comment by mahdi-torabi** [comment]
`${{ github.run_id }}` is used as the runner label and passed to action runner registration script. The reason for using this value was to ensure uniqueness. It is also a security/safety measure to avoid having a workflow accidentally target a runner launched by a different workflow. 

Since they would span over multiple workflows, those errors are become near impossible to track down. 

Would adding a custom prefix to `${{ github.run_id }}` do the job ? Or you think we should have the ability to override the whole thing ? 

I am open to both possibilities but the second one (overriding the whole label) as the risk described above associated with. 

As for the first scenario with the prefix, say if you specify `action_runner_label_prefix: "xyz"`, then you can target the runner as `runs-on: xyz${{ github.run_id }}`

**Comment by yuravk** [comment]
Actually, it works for me now "as is".

The runners are named like `${{github.run_id}}-${instance_hostname}`, and the EC2 instance hostname includes unique private IP address, so runners' names differ.

The `action_runner_label_prefix: ${{ matrix.smth }}` and later `runs-on: ${{ matrix.smth }}${{ github.run_id }}` sound reasonable in my case. But as it works, you may postpone with the implementation. Nobody else seams need this functionality.

Thank you.

**Comment by mahdi-torabi** [comment]
I recall working on ensuring unique runner names/ids when looking into docker support. I was a bit surprised as to why wouldn't it work with a matrix. 

I'll close this for now and if someone else asks for it then we can look into it.

Thanks for confirming that it works.

**Comment by yuravk** [comment]
I would like the feature request is reopened.

I'm widely using the action, and appreciate your work very much.

On my recent workflow, the action creates runners on [AlmaLinux OS](https://almalinux.org)'s different releases, like `8.*` and `9.*`
And sometimes, the next job (which relies on the specific release), starts on like  "a wrong" runner: job for the `8` release runs on the runner with `9` ...

So, if it's possible, I would like to have an ability to set for the action `action_runner_label_prefix: ${{ matrix.smth }}` and in depended jobs use `runs-on: ${{ matrix.smth }}${{ github.run_id }}`
